#
# 14_VariableSelection_Subset6_final.R
#
# This script is modified on the top of "10_PSCL_Analysis.R"
#
# Purpose: stepwise addition to select variable to be included in the model.
#
# Instead of using negation of pattern to find the subset without a match, a simplier way is to use the "invert" option of "grep".
# (approach 1): grep("[^Stk_120_cnt]",c(X.var.num,X.var.cat),value=TRUE,invert=TRUE) to find out those entries in c(X.var.num,X.var.cat) which is not "Stk_120_cnt".  Please note: this will be wrongly exclude "Stk_12_cnt" in c(X.var.num,X.var.cat)
# (approach 2): grep("Stk_120_cnt",c(X.var.num,X.var.cat),value=TRUE,invert=TRUE)
#
#
# purpose: keey variables for each subset (by checking the plots generated by "12_Prep_Subset_Data.R") and use pscl to model it.
#
# -------------------------------------------------------------------------------------------------
# June 8, 2013: This is to check the subset data created by "12_Prep_Subset_Data.R" mainly on checking the re-grouping of lithology and particle size categorical variables.
#
# June 7, 2013: Chris M provided the re-group rules for the lithology and part size categorical variables for each subset of the data.
#
# June 4, 2013
# Variables to be retained for the analysis vary in terms of subsets.
# We are going to do the following five subsets
# 1. Lower - Gillnet	  (GN14S, GN41S, GN18S, GN81S)  
# 2. Lower - Trotline	  (TLC1S, TLC2S)
# 3. Lower - active gears (OT16S and TNS and TN25S)
# 4. Upper - active gears (OT16S and TNS and TN25S)
# 5. Upper - Trotline	  (TLC1S, TLC2S)
# -------------------------------------------------------------------------------------------------
# Chris Vernon prepared a revised data sheet on May 31,   2013 after having deleted some segment 7 data.
# Chris Vernon prepared a revised data sheet on May 27,   2013 with (1) relative discharge    and (2) new field names
#
# Data difference between May 27, 2013 and May 14, 2013

# The data has been pre-processed in excel in the following way before saved as the csv format to be used by this script.
# (1) replace all 1,380,446 NULL  with empty field
# (2) replace all       142 NaN   with empty field
# (3) replace all         0 -9999 with empty field
# (4) replace 8     "#DIV/0!"     with empty field in the CPUE field
# (5) replace 8 "DIV/0!" for "CPUE" and 1 "DIV/0!" for "CPUA" and the same number for "CPUE2" and "CPUA2".
#
# eliminate all stuff
rm(list = ls(all = TRUE))


# setup start date and time
start_time <- date();
Start.time <- Sys.time()
set.seed(12345, kind = NULL)	# set seed of random number

# close all devices which are currently open
device.list <- dev.list()
if (length(device.list) != 0){for (device.this in device.list){dev.off(device.this)}}


# today's month, day and year in the format of "Thu Jun 16 08:48:36 2011", 5 fields separated by space
today.month  <- strsplit(date(),"\\s+",perl=TRUE)[[1]][2]
today.day    <- strsplit(date(),"\\s+",perl=TRUE)[[1]][3]
today.year   <- strsplit(date(),"\\s+",perl=TRUE)[[1]][5]
today.hour   <- strsplit(strsplit(date(),"\\s+",perl=TRUE)[[1]][4],":",perl=TRUE)[[1]][1]
today.minute <- strsplit(strsplit(date(),"\\s+",perl=TRUE)[[1]][4],":",perl=TRUE)[[1]][2]
today.second <- strsplit(strsplit(date(),"\\s+",perl=TRUE)[[1]][4],":",perl=TRUE)[[1]][3]


# -------------------------------------------------------------------------------------------------
# 	change to the script directory
# ------------------------------------------------------------------------------------------------- 
if(.Platform$OS.type == "unix") 
{
	Path.Current <- "C:/YuLong_Projects/FY2012_MORiver/DataAnalysis/0_scripts"
}else{
	Path.Current <- "C:/YuLong_Projects/FY2012_MORiver/DataAnalysis/0_scripts"
}
setwd(Path.Current)

FL.package  <- paste(Path.Current,"package_loading.R",sep="/")
source(FL.package)

# Data Folder
Path.IN  <- "C:/YuLong_Projects/FY2012_MORiver/DataAnalysis/12_Prep_Subset_Data"
Path.log <- "C:/YuLong_Projects/FY2012_MORiver/DataAnalysis/0_log"												
Path.OUT <- "C:/YuLong_Projects/FY2012_MORiver/DataAnalysis/14_VariableSelection_final"
if (!file.exists(Path.IN)) {stop(paste(" INPUT data folder does NOT exist!\n",sep=""))}
if (!file.exists(Path.log)){print(paste("NOT existing:",Path.log));dir.create(Path.log,showWarnings=TRUE,recursive=TRUE)}
if (!file.exists(Path.OUT)){print(paste("NOT existing:",Path.OUT));dir.create(Path.OUT,showWarnings=TRUE,recursive=TRUE)}

# data file
FL.OBJ.IN <- paste(Path.IN, "12_Prep_Subset_Data.RData", sep="/")
FL.LOG    <- paste(Path.log,"14_VariableSelection_Subset6_final.log",sep="/")	
if (!file.exists(FL.OBJ.IN)){stop(paste(" INPUT data file   does NOT exist!\n",sep=""))}
if  (file.exists(FL.LOG))   {print(paste(FL.LOG,      "exist.Delete it!")); file.remove(FL.LOG)}


FL.ReGroup.SUM <- paste(Path.OUT, paste("ReGrouping_Summary.csv",sep=""),sep="/")
if  (file.exists(FL.ReGroup.SUM)){print(paste(FL.ReGroup.SUM,"exist.Delete it!")); file.remove(FL.ReGroup.SUM)}


FL.RESL.OUT <- paste(Path.OUT,"14_VariableSelection_Subset6_final.csv",sep="/")
if  (file.exists(FL.RESL.OUT)) {print(paste(FL.RESL.OUT,"exist.Delete it!")); file.remove(FL.RESL.OUT)}

# -----------------------------------------------------------------------
# function
# -----------------------------------------------------------------------
model.output = function(Model.ID,model.string,model.count,model.no.var,model.formula,model.coef,model.sum,model.data.fit,var.rm) 
{
	null.df        <- model.sum[1]
	resi.df        <- model.sum[2]
	null.deviance  <- model.sum[3]
	resi.deviance  <- model.sum[4]
	aic            <- model.sum[5]
	iter           <- model.sum[6]

	# write the model out 
	model.coef[,"signif"] <- rep("",dim(model.coef)[1])
	model.coef[model.coef[,"Pr(>|z|)"] <= 0.001,"signif"]                                  <- "***"
	model.coef[model.coef[,"Pr(>|z|)"] >  0.001 & model.coef[,"Pr(>|z|)"] < 0.01,"signif"] <- " **"
	model.coef[model.coef[,"Pr(>|z|)"] >  0.01  & model.coef[,"Pr(>|z|)"] < 0.05,"signif"] <- "  *"
	model.coef[model.coef[,"Pr(>|z|)"] >  0.05  & model.coef[,"Pr(>|z|)"] < 0.10,"signif"] <- "  ."
	
	model.out.line1     <- paste("Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1",sep=" ")
	model.null.deviance <- paste("    Null deviance:",round(null.deviance,digits=1),"on",null.df,    "degree of freedom",sep=" ")
	model.resi.deviance <- paste("Residual deviance:",round(resi.deviance,digits=1),"on",resi.df,"degree of freedom",sep=" ")
	model.aic           <- paste("AIC:",round(aic,digits=1),sep=" ")
	model.iter          <- paste("Number of Fisher Scoring iterations:",iter,sep=" ")


	# cat(paste("Call:\n",model.formula,"\n",sep=""),file=FL.OUT.Model,append=TRUE)
	cat(paste(model.string,            sep=""),file=FL.OUT.Model,append=TRUE)
	cat(paste("Coefficients:\n",       sep=""),file=FL.OUT.Model,append=TRUE)
	write.table(model.coef,file=FL.OUT.Model,row.names=TRUE,col.names=TRUE,sep=",",append=TRUE)
	cat(paste(model.out.line1,"\n",    sep=""),file=FL.OUT.Model,append=TRUE)
	cat(paste(model.null.deviance,"\n",sep=""),file=FL.OUT.Model,append=TRUE)
	cat(paste(model.resi.deviance,"\n",sep=""),file=FL.OUT.Model,append=TRUE)
	cat(paste(model.aic,"\n",          sep=""),file=FL.OUT.Model,append=TRUE)
	cat(paste(model.iter,"\n",         sep=""),file=FL.OUT.Model,append=TRUE)
	cat(paste("\n\n",                  sep=""),file=FL.OUT.Model,append=TRUE)

	cat(paste(model.ID,",",            sep=""),file=FL.OUT.Data,append=TRUE)
	write.table(model.data.fit,file=FL.OUT.Data,row.names=TRUE,col.names=TRUE,sep=",",append=TRUE)

	# put summary into the summary array
	summary.this <- c(ID       = Model.ID,
			  model.idx= model.count,
			  var.rm   = var.rm,
			  no.var   = model.no.var,
			  dev.null = round(null.deviance,digits=1),
			  df.null  = null.df,
			  dev.res  = round(resi.deviance,digits=1),
			  df.res   = resi.df,
			  AIC      = round(aic,digits=1))

	return(summary.this)
}



# ******************************************************************
# Loop of Subsets
# ******************************************************************
subsets.section <- c("Upper","Upper","Lower","Lower","Lower","Upper",   "Lower",   "All")
subsets.gear    <- c("OT_TN","TLC",  "OT_TN","TLC",  "GN",   "Logistic","Logistic","All")
for (idx.subset in c(6))
{
	# -------------------------------------------------------------------------------------------------
	# 1. name subset and save them in the binary R data file
	# -------------------------------------------------------------------------------------------------
	subset.section <- subsets.section[idx.subset]
	subset.gear    <- subsets.gear[idx.subset]


	#
	# prepare INPUT DATA FILE
	#
	Path.IN.subset  <- paste(Path.IN, paste(paste("subset",idx.subset,sep=""),subset.section,subset.gear,sep="_"),sep="/")
	Path.OUT.subset <- paste(Path.OUT,paste(paste("subset",idx.subset,sep=""),subset.section,subset.gear,sep="_"),sep="/")
	if (!file.exists(Path.OUT.subset)){print(paste("NOT existing:",Path.OUT.subset));dir.create(Path.OUT.subset,showWarnings=TRUE,recursive=TRUE)}
	if (!file.exists(Path.IN.subset)) {print(paste("NOT existing:",Path.IN.subset," Check Why!\n",sep=""));die}
	
	#
	# load the data
	#
	load(FL.OBJ.IN)
	cat(paste("0. [",FL.OBJ.IN,"] has been loaded!\n",sep=""))
	cat(paste("0. [",FL.OBJ.IN,"] has been loaded!\n",sep=""),file=FL.LOG,append=TRUE)
	

	cat(paste("\n\n************************************ [",subset.gear,"] and [",subset.section,"] ","************************************","\n",sep=""))
	cat(paste("\n\n************************************ [",subset.gear,"] and [",subset.section,"] ","************************************","\n",sep=""),file=FL.LOG,append=TRUE)
	
	FL.OUT.Obj   <<- paste(Path.OUT.subset, paste("RData_Subset_",idx.subset,"_",subset.section,"_",subset.gear,".RData",sep=""),sep="/")
	FL.OUT.Data  <<- paste(Path.OUT.subset, paste("Data_Subset_", idx.subset,"_",subset.section,"_",subset.gear,".csv",  sep=""),sep="/")
	FL.OUT.Model <<- paste(Path.OUT.subset, paste("Model_Subset_",idx.subset,"_",subset.section,"_",subset.gear,".csv",  sep=""),sep="/")
	if  (file.exists(FL.OUT.Obj))  {print(paste(FL.OUT.Obj,  "exist.Delete it!"));file.remove(FL.OUT.Obj)}
	if  (file.exists(FL.OUT.Data)) {print(paste(FL.OUT.Data, "exist.Delete it!"));file.remove(FL.OUT.Data)}
	# if  (file.exists(FL.OUT.Model)){print(paste(FL.OUT.Model,"exist.Delete it!"));file.remove(FL.OUT.Model)}


	# subset 1: upper OT and TN (active gear) [myData.Upper_Active]
	if (idx.subset == 1)
	{		
		myData.Sub      <- myData.Upper_Active    
		col.title.4.sub <- col.title.Upper_Active  
		col.class.4.sub <- col.class.Upper_Active  	

		Y.var  <- "Pal_cnt"
		var.rm <- c("Gear","MA","Lith_1","Lith_2","Lith_desc","NFHAP","Tax_part_sz","Turb","Meso","MicroClass","WaterVel","Fish_cnt","CPUA","Stk_12_dist","Stk_24_dist","Stk_36_dist","Stk_60_dist","Stk_120_dist","Rel_dsch_AY","Rel_dsch_WY","gear.type1","gear.type2","CPUA.calc")

		
		
	# subset 2: upper TLC [myData.Upper_TLC]
	}else if(idx.subset == 2){
		myData.Sub      <- myData.Upper_TLC    
		col.title.4.sub <- col.title.Upper_TLC  
		col.class.4.sub <- col.class.Upper_TLC 	
		
		Y.var  <- "Pal_cnt"
		var.rm <- c("Gear","MA","Lith_1","Lith_2","Lith_desc","NFHAP","Tax_part_sz","Turb","Meso","MicroClass","WaterVel","Fish_cnt","CPUE","Stk_12_dist","Stk_24_dist","Stk_36_dist","Stk_60_dist","Stk_120_dist","Rel_dsch_AY","Rel_dsch_WY","gear.type1","gear.type2","CPUE.calc")
		
		
	# subset 3: lower OT & TN	[myData.Lower_Active]
	}else if(idx.subset == 3){
		myData.Sub      <- myData.Lower_Active    
		col.title.4.sub <- col.title.Lower_Active  
		col.class.4.sub <- col.class.Lower_Active 	
		
		Y.var  <- "Pal_cnt"
		var.rm <- c("Gear","D_dist_dn","D_dist_near","MA","Lith_1","Lith_2","Lith_desc","NFHAP","Tax_part_sz","Turb","Meso","WaterVel","Fish_cnt","CPUA","Stk_12_dist","Stk_24_dist","Stk_36_dist","Stk_60_dist","Stk_120_dist","Rel_dsch_AY","Rel_dsch_WY","gear.type1","gear.type2","CPUA.calc")
		
		
	# subset 4: lower TLC [myData.Lower_TLC]
	}else if(idx.subset == 4){
		myData.Sub      <- myData.Lower_TLC    
		col.title.4.sub <- col.title.Lower_TLC   
		col.class.4.sub <- col.class.Lower_TLC  	
		
		Y.var  <- "Pal_cnt"
		var.rm <- c("Gear","D_dist_dn","D_dist_near","MA","Lith_1","Lith_2","Lith_desc","NFHAP","Tax_part_sz","Turb","Meso","WaterVel","Fish_cnt","CPUE","Stk_12_dist","Stk_24_dist","Stk_36_dist","Stk_60_dist","Stk_120_dist","Rel_dsch_AY","Rel_dsch_WY","gear.type1","gear.type2","CPUE.calc")
		
	# subset 5: lower GN [myData.Lower_GN]
	}else if(idx.subset == 5){
		myData.Sub      <- myData.Lower_GN    
		col.title.4.sub <- col.title.Lower_GN   
		col.class.4.sub <- col.class.Lower_GN 	
		
		Y.var  <- "Pal_cnt"
		var.rm <- c("Gear","Season","D_dist_dn","D_dist_near","MA","Lith_1","Lith_2","Lith_desc","NFHAP","Tax_part_sz","Turb","Meso","WaterVel","Fish_cnt","CPUE","Stk_12_dist","Stk_24_dist","Stk_36_dist","Stk_60_dist","Stk_120_dist","Rel_dsch_AY","Rel_dsch_WY","gear.type1","gear.type2","CPUE.calc")
		
		
	# subset 6: Logistic Upper [myData.Upper_Logistic]
	}else if(idx.subset == 6){
		myData.Sub      <- myData.Upper_Logistic    
		col.title.4.sub <- col.title.Upper_Logistic   
		col.class.4.sub <- col.class.Upper_Logistic 
		
		Y.var  <- "binary"
		var.rm.fix <- c("Gear","MA","Lith_1","Lith_2","Lith_desc","NFHAP","Tax_part_sz","Turb","Meso","MicroClass","WaterVel","Fish_cnt","CPUE","CPUA","Stk_12_dist","Stk_24_dist","Stk_36_dist","Stk_60_dist","Stk_120_dist",                            "gear.type1","gear.type2","CPUA.calc","CPUE.calc")
		var.rm     <- c("Gear","MA","Lith_1","Lith_2","Lith_desc","NFHAP","Tax_part_sz","Turb","Meso","MicroClass","WaterVel","Fish_cnt","CPUE","CPUA","Stk_12_dist","Stk_24_dist","Stk_36_dist","Stk_60_dist","Stk_120_dist",                            "gear.type1","gear.type2","CPUA.calc","CPUE.calc")
		
		
	# subset 7: Logistic Lower [myData.Lower_Logistic]
	}else if(idx.subset == 7){
		myData.Sub      <- myData.Lower_Logistic    
		col.title.4.sub <- col.title.Lower_Logistic   
		col.class.4.sub <- col.class.Lower_Logistic 	
		
		Y.var  <- "binary"
		var.rm <- c("Gear","D_dist_dn","D_dist_near","MA","Lith_1","Lith_2","Lith_desc","NFHAP","Tax_part_sz","Turb","Meso","WaterVel","Fish_cnt","CPUE","CPUA","Stk_12_dist","Stk_24_dist","Stk_36_dist","Stk_60_dist","Stk_120_dist","Rel_dsch_AY","Rel_dsch_WY","gear.type1","gear.type2","CPUA.calc","CPUE.calc")
		
		
	# subset 8: All
	}else if(idx.subset == 8){
		myData.Sub      <- myData.All    
		col.title.4.sub <- col.title.All   
		col.class.4.sub <- col.class.All 
		
		var.rm <- c("Gear","D_dist_dn","D_dist_near","MA","Lith_1","Lith_2","Lith_desc","NFHAP","Tax_part_sz","Turb","Meso","WaterVel","Fish_cnt","CPUE","Stk_12_dist","Stk_24_dist","Stk_36_dist","Stk_60_dist","Stk_120_dist","Rel_dsch_AY","Rel_dsch_WY","gear.type1","gear.type2","CPUE.calc")
		
	}	
	
	# -----------------------------------------------------------------------------------------
	# July 10, 2013
	# remove NA rows before stepwise to ensure all variables starting with the same data
	# based on the initial assessment of the variables to be kept (not the actual variables we could be able to keep which depends on the computational singurity)
	# July 10, 2013
	# -----------------------------------------------------------------------------------------
	# naCol.2.rm: the number of missing of each variable
	# naRow.2.rm: the number of missing of each observation.  
	idxCol.2.subset <- match(var.rm.fix,names(myData.Sub))	
	naCol.2.rm <- apply(myData.Sub[,-idxCol.2.subset],2,function(x){sum(is.na(x))})
	naRow.2.rm <- apply(myData.Sub[,-idxCol.2.subset],1,function(x){sum(is.na(x))})
	if (sum(naCol.2.rm) != sum(naRow.2.rm)){cat("Something is not right!\n");die}
	idx.NA <- seq(1,dim(myData.Sub)[1])[naRow.2.rm>0]
	if(length(idx.NA)>0)
	{
		myData.Sub <- myData.Sub[-idx.NA,]
	}
	
	
	#
	# reduced data set for each subset of data
	idxCol.2.rm <- match(var.rm,names(myData.Sub))
	if(is.na(any(idxCol.2.rm))){cat(paste("Check the col names of [myDataSub] for Subset_",subset.section,"_",subset.gear,sep=""));die}
	myData.Reduced <- myData.Sub[,-idxCol.2.rm]

	
	idx.2.rm <- match(var.rm,col.title.4.sub)
	if(is.na(any(idx.2.rm))){cat(paste("Check the col names of [col.title.4.sub] for Subset_",subset.section,"_",subset.gear,sep=""));die}	
	col.title.reduced <- col.title.4.sub[-idx.2.rm]
	col.class.reduced <- col.class.4.sub[-idx.2.rm]
		
	#	
	X.var.cat    <- grep("binary",col.title.reduced[col.class.reduced == "factor"],value=TRUE,invert=TRUE)
	X.var.num    <- grep("Pal_cnt",grep("SUPPORT.calc",col.title.reduced[col.class.reduced != "factor"],value=TRUE,invert=TRUE),value=TRUE,invert=TRUE)	
	X.var.offset <- "SUPPORT.calc"
	
	#
	myData.X.num    <- myData.Reduced[,X.var.num,   drop=FALSE]
	myData.X.cat    <- myData.Reduced[,X.var.cat,   drop=FALSE] 
	myData.X.offset <- myData.Reduced[,X.var.offset,drop=FALSE]
	myData.Y        <- myData.Reduced[,Y.var,       drop=FALSE] 
	
	# make sure the categorical are factors
	for (i in names(myData.X.cat))
	{
		if (!(is.factor(myData.X.cat[,i])))
		{
			myData.X.cat[,i] <- as.factor(myData.X.cat[,i])
		}
	}

	# standardized the numerical variables
	var.mean <- as.data.frame(matrix(rep(apply(myData.X.num,2,mean,na.rm=TRUE),dim(myData.X.num)[1]),nrow=dim(myData.X.num)[1],byrow=TRUE))
	var.sd   <- as.data.frame(matrix(rep(apply(myData.X.num,2,sd,na.rm=TRUE),  dim(myData.X.num)[1]),nrow=dim(myData.X.num)[1],byrow=TRUE))
	myData.X.num.std <- (myData.X.num - var.mean)/var.sd
	
	if(idx.subset == 6)	# Logistic Regression for Upper River
	{
		# [Subset 6 Logistic Regression on Upper River]: define an empty array to hold model summary
		model.count <- 0
		summary.out <- c()
		
		# compile a working data set
		myData.Work <- cbind(myData.Y,myData.X.num.std,myData.X.cat)

		# remove rows with NA
		naRow.2.rm <- apply(myData.Work,1,function(x){sum(is.na(x))})
		idx.NA <- seq(1,dim(myData.Work)[1])[naRow.2.rm>0]
		if(length(idx.NA)>0)
		{
			myData.Work <- myData.Work[-idx.NA,]
		}

		# ---------------------------------------------------------------------------------
		# [Subset 6 Logistic Regression on Upper River]: 1. model with 1 variable (one variable)
		# ---------------------------------------------------------------------------------
		save.command <- ""
		no.tmp  <- length(c(X.var.num,X.var.cat))
		idx.tmp <- 0
		for (X.var.rm in c(X.var.num,X.var.cat))
		{
			idx.tmp <- idx.tmp + 1
			idx.var.rm <- match(X.var.rm,names(myData.Work))				# the index of the variable to be removed in the data frame
			if(!(is.na(idx.var.rm)))
			{
				model.count  <- model.count + 1
				myData.Tmp   <- myData.Work[,c("binary",X.var.rm)]
				model.Tmp    <- glm(binary ~ .,data=myData.Tmp,family=binomial("logit"))
				model.ID     <- X.var.rm
				model.string <- paste("Model",model.count," with ",X.var.rm,"\n",sep=" ")
				model.no.var <- dim(myData.Tmp)[2] - 1
				model.rm.var <- paste("all but",X.var.rm,sep=" ")
		
				model.formula       <- summary(model.Tmp)$call
				model.coef          <- as.data.frame(summary(model.Tmp)$coef)
				model.sum           <- c(summary(model.Tmp)$df.null,		 # null.df        
							 summary(model.Tmp)$df.residual,	 # resi.df        
							 summary(model.Tmp)$null.deviance,	 # null.deviance  
							 summary(model.Tmp)$deviance,		 # resi.deviance  
							 summary(model.Tmp)$aic,		 # aic            
							 summary(model.Tmp)$iter)		 # iter     
				model.data.fit      <- cbind(model.Tmp$data,fitted.value=model.Tmp$fitted.values,residual=model.Tmp$residual)		                         
		
				summary.this <- model.output(model.ID,model.string,model.count,model.no.var,model.formula,model.coef,model.sum,model.data.fit,model.rm.var)
		
				if (model.count == 1){summary.out <- summary.this}else{summary.out <- rbind(summary.out,summary.this)}
				
				# assign the model coefficienct to an object 
				command.string <- paste(paste("MODEL.1_",X.var.rm,sep="")," <- model.coef",sep="")
				eval(parse(text=command.string))
				
		
				save.command <- paste(save.command,",",paste("MODEL.1_",X.var.rm,sep=""),sep="")					# for all other model than the last one
			      # save.command <- paste(save.command,",",paste("MODEL.1_",X.var.rm,sep=""),",file=\"",FL.OUT.Obj,"\")",sep="")	# FOR THE LAST MODEL
			}
		}
		cat(paste("1. model with all 1 variable\n",sep=""))
		cat(paste("1. model with all 1 variable\n",sep=""),file=FL.LOG,append=TRUE)		
		

		# ---------------------------------------------------------------------------------
		# [Subset 6 Logistic Regression on Upper River]: 2. model with 2 variables: "Stk_120_cnt" is best single
		# ---------------------------------------------------------------------------------
		no.tmp  <- length(c(X.var.num,X.var.cat))
		idx.tmp <- 0
		for (X.var.rm in grep("Stk_120_cnt",c(X.var.num,X.var.cat),value=TRUE,invert=TRUE))		# all variables other than "Stk_120_cnt"
		{
			idx.tmp <- idx.tmp + 1
			idx.var.rm <- match(X.var.rm,names(myData.Work))				# the index of the variable to be removed in the data frame
			if(!(is.na(idx.var.rm)))
			{
				model.count  <- model.count + 1
				myData.Tmp   <- myData.Work[,c("binary","Stk_120_cnt",X.var.rm)]	# two variable combinations: "Stk_120_cnt" and the other
				model.Tmp    <- glm(binary ~ .,data=myData.Tmp,family=binomial("logit"))
				model.ID     <- X.var.rm
				model.string <- paste("Model",model.count," with ",X.var.rm," & Stk_120_cnt\n",sep=" ")
				model.no.var <- dim(myData.Tmp)[2] - 1
				model.rm.var <- paste("all but Stk_120_cnt & ",X.var.rm,sep=" ")
		
				model.formula       <- summary(model.Tmp)$call
				model.coef          <- as.data.frame(summary(model.Tmp)$coef)
				model.sum           <- c(summary(model.Tmp)$df.null,		 # null.df        
							 summary(model.Tmp)$df.residual,	 # resi.df        
							 summary(model.Tmp)$null.deviance,	 # null.deviance  
							 summary(model.Tmp)$deviance,		 # resi.deviance  
							 summary(model.Tmp)$aic,		 # aic            
							 summary(model.Tmp)$iter)		 # iter     
				model.data.fit      <- cbind(model.Tmp$data,fitted.value=model.Tmp$fitted.values,residual=model.Tmp$residual)		                         
		
				summary.this <- model.output(model.ID,model.string,model.count,model.no.var,model.formula,model.coef,model.sum,model.data.fit,model.rm.var)
		
				if (model.count == 1){summary.out <- summary.this}else{summary.out <- rbind(summary.out,summary.this)}
				
				# assign the model coefficienct to an object 
				command.string <- paste(paste("MODEL.2_",X.var.rm,sep="")," <- model.coef",sep="")
				eval(parse(text=command.string))
				
		
				save.command <- paste(save.command,",",paste("MODEL.2_",X.var.rm,sep=""),sep="")				# for all other model than the last one
			      # save.command <- paste(save.command,",",paste("MODEL.2_",X.var.rm,sep=""),",file=\"",FL.OUT.Obj,"\")",sep="")	# FOR THE LAST MODEL
			}
		}
		cat(paste("2. model with the best one and another one variable\n",sep=""))
		cat(paste("2. model with the best one and another one variable\n",sep=""),file=FL.LOG,append=TRUE)		
		
	
	
		# ---------------------------------------------------------------------------------
		# [Subset 6 Logistic Regression on Upper River]: 3. model with 3 variables: ["Stk_120_cnt"] & ["Rel_dsch_AY"] and another one (three variables): "Rel_dsch_AY" is te second best single with "Stk_120_cnt"
		# ---------------------------------------------------------------------------------
		no.tmp  <- length(c(X.var.num,X.var.cat))
		idx.tmp <- 0
		for (X.var.rm in grep("Rel_dsch_AY",grep("Stk_120_cnt",c(X.var.num,X.var.cat),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE))		# all variables other than "Rel_dsch_AY", "Stk_120_cnt"
		{
			idx.tmp <- idx.tmp + 1
			idx.var.rm <- match(X.var.rm,names(myData.Work))							# the index of the variable to be removed in the data frame
			if(!(is.na(idx.var.rm)))
			{
				model.count  <- model.count + 1
				myData.Tmp   <- myData.Work[,c("binary","Stk_120_cnt","Rel_dsch_AY",X.var.rm)]			# three variable combinations: "Stk_120_cnt", "Rel_dsch_AY" and the other
				model.Tmp    <- glm(binary ~ .,data=myData.Tmp,family=binomial("logit"))
				model.ID     <- X.var.rm
				model.string <- paste("Model",model.count," with ",X.var.rm," & Stk_120_cnt/Rel_dsch_AY\n",sep=" ")
				model.no.var <- dim(myData.Tmp)[2] - 1
				model.rm.var <- paste("all but Stk_120_cnt/Rel_dsch_AY & ",X.var.rm,sep=" ")
		
				model.formula       <- summary(model.Tmp)$call
				model.coef          <- as.data.frame(summary(model.Tmp)$coef)
				model.sum           <- c(summary(model.Tmp)$df.null,		 # null.df        
							 summary(model.Tmp)$df.residual,	 # resi.df        
							 summary(model.Tmp)$null.deviance,	 # null.deviance  
							 summary(model.Tmp)$deviance,		 # resi.deviance  
							 summary(model.Tmp)$aic,		 # aic            
							 summary(model.Tmp)$iter)		 # iter     
				model.data.fit      <- cbind(model.Tmp$data,fitted.value=model.Tmp$fitted.values,residual=model.Tmp$residual)		                         
		
				summary.this <- model.output(model.ID,model.string,model.count,model.no.var,model.formula,model.coef,model.sum,model.data.fit,model.rm.var)
		
				if (model.count == 1){summary.out <- summary.this}else{summary.out <- rbind(summary.out,summary.this)}
				
				# assign the model coefficienct to an object 
				command.string <- paste(paste("MODEL.3_",X.var.rm,sep="")," <- model.coef",sep="")
				eval(parse(text=command.string))
				
		
				save.command <- paste(save.command,",",paste("MODEL.3_",X.var.rm,sep=""),sep="")				# for all other model than the last one
			      # save.command <- paste(save.command,",",paste("MODEL.3_",X.var.rm,sep=""),",file=\"",FL.OUT.Obj,"\")",sep="")	# FOR THE LAST MODEL
			}
		}
		cat(paste("3. model with the best one and another one variable\n",sep=""))
		cat(paste("3. model with the best one and another one variable\n",sep=""),file=FL.LOG,append=TRUE)		
		
		
		# ---------------------------------------------------------------------------------
		# [Subset 6 Logistic Regression on Upper River]: 4. model with 4 variables: ["macro.typement"], ["Stk_120_cnt"] & ["Rel_dsch_AY"] and another one (three variables):  "macro.typement" is the third best single with "Stk_120_cnt", "Rel_dsch_AY"
		# ---------------------------------------------------------------------------------
		no.tmp  <- length(c(X.var.num,X.var.cat))
		idx.tmp <- 0
		for (X.var.rm in grep("macro.type",grep("Rel_dsch_AY",grep("Stk_120_cnt",c(X.var.num,X.var.cat),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE))		# all variables other than "macro.type", "Rel_dsch_AY", "Stk_120_cnt"
		{
			idx.tmp <- idx.tmp + 1
			idx.var.rm <- match(X.var.rm,names(myData.Work))							# the index of the variable to be removed in the data frame
			if(!(is.na(idx.var.rm)))
			{
				model.count  <- model.count + 1
				myData.Tmp   <- myData.Work[,c("binary","Stk_120_cnt","Rel_dsch_AY","macro.type",X.var.rm)]			# three variable combinations: "Stk_120_cnt", "Rel_dsch_AY" and the other
				model.Tmp    <- glm(binary ~ .,data=myData.Tmp,family=binomial("logit"))
				model.ID     <- X.var.rm
				model.string <- paste("Model",model.count," with ",X.var.rm," & Stk_120_cnt/Rel_dsch_AY/macro.type\n",sep=" ")
				model.no.var <- dim(myData.Tmp)[2] - 1
				model.rm.var <- paste("all but Stk_120_cnt/Rel_dsch_AY/macro.type & ",X.var.rm,sep=" ")
		
				model.formula       <- summary(model.Tmp)$call
				model.coef          <- as.data.frame(summary(model.Tmp)$coef)
				model.sum           <- c(summary(model.Tmp)$df.null,		 # null.df        
							 summary(model.Tmp)$df.residual,	 # resi.df        
							 summary(model.Tmp)$null.deviance,	 # null.deviance  
							 summary(model.Tmp)$deviance,		 # resi.deviance  
							 summary(model.Tmp)$aic,		 # aic            
							 summary(model.Tmp)$iter)		 # iter     
				model.data.fit      <- cbind(model.Tmp$data,fitted.value=model.Tmp$fitted.values,residual=model.Tmp$residual)		                         
		
				summary.this <- model.output(model.ID,model.string,model.count,model.no.var,model.formula,model.coef,model.sum,model.data.fit,model.rm.var)
		
				if (model.count == 1){summary.out <- summary.this}else{summary.out <- rbind(summary.out,summary.this)}
				
				# assign the model coefficienct to an object 
				command.string <- paste(paste("MODEL.4_",X.var.rm,sep="")," <- model.coef",sep="")
				eval(parse(text=command.string))
				
		
				save.command <- paste(save.command,",",paste("MODEL.4_",X.var.rm,sep=""),sep="")				# for all other model than the last one
			      # save.command <- paste(save.command,",",paste("MODEL.4_",X.var.rm,sep=""),",file=\"",FL.OUT.Obj,"\")",sep="")	# FOR THE LAST MODEL
			}
		}
		cat(paste("4. model with the best one and another one variable\n",sep=""))
		cat(paste("4. model with the best one and another one variable\n",sep=""),file=FL.LOG,append=TRUE)		
				

		# ---------------------------------------------------------------------------------
		# [Subset 6 Logistic Regression on Upper River]: 5. model with 5 variables: ["macro.type"], ["Segment"], ["Stk_120_cnt"] & ["Season"] and another one (three variables): ["macro.type"] is the fourth best single with "Stk_120_cnt", "Season", "Segment"
		# ---------------------------------------------------------------------------------
		no.tmp  <- length(c(X.var.num,X.var.cat))
		idx.tmp <- 0
		for (X.var.rm in grep("Season",grep("macro.type",grep("Rel_dsch_AY",grep("Stk_120_cnt",c(X.var.num,X.var.cat),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE))		# all variables other than  "macro.type", "Seg", "Season", "Stk_120_cnt",
		{
			idx.tmp <- idx.tmp + 1
			idx.var.rm <- match(X.var.rm,names(myData.Work))									# the index of the variable to be removed in the data frame
			if(!(is.na(idx.var.rm)))
			{
				model.count  <- model.count + 1
				myData.Tmp   <- myData.Work[,c("binary","Stk_120_cnt","Rel_dsch_AY","macro.type","Season",X.var.rm)]			# five variable combinations: "macro.type", "Seg","Stk_120_cnt", "Season" and the other
				model.Tmp    <- glm(binary ~ .,data=myData.Tmp,family=binomial("logit"))
				model.ID     <- X.var.rm
				model.string <- paste("Model",model.count," with ",X.var.rm," &  Stk_120_cnt/Rel_dsch_AY/macro.type/Season\n",sep=" ")
				model.no.var <- dim(myData.Tmp)[2] - 1
				model.rm.var <- paste("all but  Stk_120_cnt/Rel_dsch_AY/macro.type/Season & ",X.var.rm,sep=" ")
		
				model.formula       <- summary(model.Tmp)$call
				model.coef          <- as.data.frame(summary(model.Tmp)$coef)
				model.sum           <- c(summary(model.Tmp)$df.null,		 # null.df        
							 summary(model.Tmp)$df.residual,	 # resi.df        
							 summary(model.Tmp)$null.deviance,	 # null.deviance  
							 summary(model.Tmp)$deviance,		 # resi.deviance  
							 summary(model.Tmp)$aic,		 # aic            
							 summary(model.Tmp)$iter)		 # iter     
				model.data.fit      <- cbind(model.Tmp$data,fitted.value=model.Tmp$fitted.values,residual=model.Tmp$residual)		                         
		
				summary.this <- model.output(model.ID,model.string,model.count,model.no.var,model.formula,model.coef,model.sum,model.data.fit,model.rm.var)
		
				if (model.count == 1){summary.out <- summary.this}else{summary.out <- rbind(summary.out,summary.this)}
				
				# assign the model coefficienct to an object 
				command.string <- paste(paste("MODEL.5_",X.var.rm,sep="")," <- model.coef",sep="")
				eval(parse(text=command.string))
				
		
				save.command <- paste(save.command,",",paste("MODEL.5_",X.var.rm,sep=""),sep="")				# for all other model than the last one
			      # save.command <- paste(save.command,",",paste("MODEL.5_",X.var.rm,sep=""),",file=\"",FL.OUT.Obj,"\")",sep="")	# FOR THE LAST MODEL
			}
		}
		cat(paste("5. model with the best one and another one variable\n",sep=""))
		cat(paste("5. model with the best one and another one variable\n",sep=""),file=FL.LOG,append=TRUE)		
				
		# ---------------------------------------------------------------------------------
		# [Subset 6 Logistic Regression on Upper River]: 6. model with 6 variables: ["SY"], ["macro.type"], ["Segment"], ["Stk_120_cnt"] & ["Season"] and another one (three variables):  ["SY"] is the fifth best single with "Stk_120_cnt", "Season", "Segment", ["macro.type"]
		# ---------------------------------------------------------------------------------
		no.tmp  <- length(c(X.var.num,X.var.cat))
		idx.tmp <- 0
		for (X.var.rm in grep("Seg",grep("Season",grep("macro.type",grep("Rel_dsch_AY",grep("Stk_120_cnt",c(X.var.num,X.var.cat),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE))		# all variables other than  "SY", "macro.type", "Seg", "Season", "Stk_120_cnt",
		{
			idx.tmp <- idx.tmp + 1
			idx.var.rm <- match(X.var.rm,names(myData.Work))										# the index of the variable to be removed in the data frame
			if(!(is.na(idx.var.rm)))
			{
				model.count  <- model.count + 1
				myData.Tmp   <- myData.Work[,c("binary","Stk_120_cnt","Rel_dsch_AY","macro.type","Season","Seg",X.var.rm)]			# six variable combinations: "SY", "macro.type", "Seg","Stk_120_cnt", "Season" and the other
				model.Tmp    <- glm(binary ~ .,data=myData.Tmp,family=binomial("logit"))
				model.ID     <- X.var.rm
				model.string <- paste("Model",model.count," with ",X.var.rm," & Stk_120_cnt/Rel_dsch_AY/macro.type/Season/Seg\n",sep=" ")
				model.no.var <- dim(myData.Tmp)[2] - 1
				model.rm.var <- paste("all but Stk_120_cnt/Rel_dsch_AY/macro.type/Season/Seg & ",X.var.rm,sep=" ")
		
				model.formula       <- summary(model.Tmp)$call
				model.coef          <- as.data.frame(summary(model.Tmp)$coef)
				model.sum           <- c(summary(model.Tmp)$df.null,		 # null.df        
							 summary(model.Tmp)$df.residual,	 # resi.df        
							 summary(model.Tmp)$null.deviance,	 # null.deviance  
							 summary(model.Tmp)$deviance,		 # resi.deviance  
							 summary(model.Tmp)$aic,		 # aic            
							 summary(model.Tmp)$iter)		 # iter     
				model.data.fit      <- cbind(model.Tmp$data,fitted.value=model.Tmp$fitted.values,residual=model.Tmp$residual)		                         
		
				summary.this <- model.output(model.ID,model.string,model.count,model.no.var,model.formula,model.coef,model.sum,model.data.fit,model.rm.var)
		
				if (model.count == 1){summary.out <- summary.this}else{summary.out <- rbind(summary.out,summary.this)}
				
				# assign the model coefficienct to an object 
				command.string <- paste(paste("MODEL.6_",X.var.rm,sep="")," <- model.coef",sep="")
				eval(parse(text=command.string))
				
		
				save.command <- paste(save.command,",",paste("MODEL.6_",X.var.rm,sep=""),sep="")				# for all other model than the last one
			      # save.command <- paste(save.command,",",paste("MODEL.6_",X.var.rm,sep=""),",file=\"",FL.OUT.Obj,"\")",sep="")	# FOR THE LAST MODEL
			}
		}
		cat(paste("6. model with the best one and another one variable\n",sep=""))
		cat(paste("6. model with the best one and another one variable\n",sep=""),file=FL.LOG,append=TRUE)		
				
		# ---------------------------------------------------------------------------------
		# [Subset 6 Logistic Regression on Upper River]: 7. model with 7 variables: ["Sand_per"], ["SY"], ["macro.type"], ["Segment"], ["Stk_120_cnt"] & ["Season"] and another one (three variables):  "Sand_per" is the sixth best single with "Stk_120_cnt", "Season", "Segment", ["macro.type"], ["SY"]
		# ---------------------------------------------------------------------------------
		no.tmp  <- length(c(X.var.num,X.var.cat))
		idx.tmp <- 0
		for (X.var.rm in  grep("SY",grep("Seg",grep("Season",grep("macro.type",grep("Rel_dsch_AY",grep("Stk_120_cnt",c(X.var.num,X.var.cat),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE))		# all variables other than  "Sand_per", "SY", "macro.type", "Seg", "Season", "Stk_120_cnt",
		{
			idx.tmp <- idx.tmp + 1
			idx.var.rm <- match(X.var.rm,names(myData.Work))										# the index of the variable to be removed in the data frame
			if(!(is.na(idx.var.rm)))
			{
				model.count  <- model.count + 1
				myData.Tmp   <- myData.Work[,c("binary","Stk_120_cnt","Rel_dsch_AY","macro.type","Season","Seg","SY",X.var.rm)]			# seven variable combinations: "Sand_per", "SY", "macro.type", "Seg","Stk_120_cnt", "Season" and the other
				model.Tmp    <- glm(binary ~ .,data=myData.Tmp,family=binomial("logit"))
				model.ID     <- X.var.rm
				model.string <- paste("Model",model.count," with ",X.var.rm," & Stk_120_cnt/Rel_dsch_AY/macro.type/Season/Seg/SY\n",sep=" ")
				model.no.var <- dim(myData.Tmp)[2] - 1
				model.rm.var <- paste("all but Stk_120_cnt/Rel_dsch_AY/macro.type/Season/Seg/SY & ",X.var.rm,sep=" ")
		
				model.formula       <- summary(model.Tmp)$call
				model.coef          <- as.data.frame(summary(model.Tmp)$coef)
				model.sum           <- c(summary(model.Tmp)$df.null,		 # null.df        
							 summary(model.Tmp)$df.residual,	 # resi.df        
							 summary(model.Tmp)$null.deviance,	 # null.deviance  
							 summary(model.Tmp)$deviance,		 # resi.deviance  
							 summary(model.Tmp)$aic,		 # aic            
							 summary(model.Tmp)$iter)		 # iter     
				model.data.fit      <- cbind(model.Tmp$data,fitted.value=model.Tmp$fitted.values,residual=model.Tmp$residual)		                         
		
				summary.this <- model.output(model.ID,model.string,model.count,model.no.var,model.formula,model.coef,model.sum,model.data.fit,model.rm.var)
		
				if (model.count == 1){summary.out <- summary.this}else{summary.out <- rbind(summary.out,summary.this)}
				
				# assign the model coefficienct to an object 
				command.string <- paste(paste("MODEL.7_",X.var.rm,sep="")," <- model.coef",sep="")
				eval(parse(text=command.string))
				
		
				save.command <- paste(save.command,",",paste("MODEL.7_",X.var.rm,sep=""),sep="")				# for all other model than the last one
			      # save.command <- paste(save.command,",",paste("MODEL.7_",X.var.rm,sep=""),",file=\"",FL.OUT.Obj,"\")",sep="")	# FOR THE LAST MODEL
			}
		}
		cat(paste("7. model with the best one and another one variable\n",sep=""))
		cat(paste("7. model with the best one and another one variable\n",sep=""),file=FL.LOG,append=TRUE)		
				

				
		# ---------------------------------------------------------------------------------
		# [Subset 6 Logistic Regression on Upper River]: 8. model with 8 variables: ["Temp"], ["Sand_per"], ["SY"], ["macro.type"], ["Segment"], ["Stk_130_cnt"] & ["Season"] and another one (three variables):  "Temp" is the seventh best single with "Stk_130_cnt", "Season", "Segment", ["macro.type"], ["SY"], ["Sand_per"]
		# ---------------------------------------------------------------------------------
		no.tmp  <- length(c(X.var.num,X.var.cat))
		idx.tmp <- 0
		for (X.var.rm in  grep("T_dist_up",grep("SY",grep("Seg",grep("Season",grep("macro.type",grep("Rel_dsch_AY",grep("Stk_120_cnt",c(X.var.num,X.var.cat),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE))		# all variables other than  "Temp","Sand_per", "SY", "macro.type", "Seg", "Season", "Stk_120_cnt",
		{
			idx.tmp <- idx.tmp + 1
			idx.var.rm <- match(X.var.rm,names(myData.Work))										# the index of the variable to be removed in the data frame
			if(!(is.na(idx.var.rm)))
			{
				model.count  <- model.count + 1
				myData.Tmp   <- myData.Work[,c("binary","Stk_120_cnt","Rel_dsch_AY","macro.type","Season","Seg","SY","T_dist_up",X.var.rm)]			# eight variable combinations: "Temp","Sand_per", "SY", "macro.type", "Seg","Stk_120_cnt", "Season" and the other
				model.Tmp    <- glm(binary ~ .,data=myData.Tmp,family=binomial("logit"))
				model.ID     <- X.var.rm
				model.string <- paste("Model",model.count," with ",X.var.rm," & Stk_120_cnt/Rel_dsch_AY/macro.type/Season/Seg/SY/T_dist_up\n",sep=" ")
				model.no.var <- dim(myData.Tmp)[2] - 1
				model.rm.var <- paste("all but Stk_120_cnt/Rel_dsch_AY/macro.type/Season/Seg/SY/T_dist_up & ",X.var.rm,sep=" ")
		
				model.formula       <- summary(model.Tmp)$call
				model.coef          <- as.data.frame(summary(model.Tmp)$coef)
				model.sum           <- c(summary(model.Tmp)$df.null,		 # null.df        
							 summary(model.Tmp)$df.residual,	 # resi.df        
							 summary(model.Tmp)$null.deviance,	 # null.deviance  
							 summary(model.Tmp)$deviance,		 # resi.deviance  
							 summary(model.Tmp)$aic,		 # aic            
							 summary(model.Tmp)$iter)		 # iter     
				model.data.fit      <- cbind(model.Tmp$data,fitted.value=model.Tmp$fitted.values,residual=model.Tmp$residual)		                         
				
				summary.this <- model.output(model.ID,model.string,model.count,model.no.var,model.formula,model.coef,model.sum,model.data.fit,model.rm.var)
		
				if (model.count == 1){summary.out <- summary.this}else{summary.out <- rbind(summary.out,summary.this)}
				
				# assign the model coefficienct to an object 
				command.string <- paste(paste("MODEL.8_",X.var.rm,sep="")," <- model.coef",sep="")
				eval(parse(text=command.string))
		
				save.command <- paste(save.command,",",paste("MODEL.8_",X.var.rm,sep=""),sep="")				# for all other model than the last one
			      # save.command <- paste(save.command,",",paste("MODEL.8_",X.var.rm,sep=""),",file=\"",FL.OUT.Obj,"\")",sep="")	# FOR THE LAST MODEL
			}
		}
		cat(paste("8. model with the best one and another one variable\n",sep=""))
		cat(paste("8. model with the best one and another one variable\n",sep=""),file=FL.LOG,append=TRUE)		
				
									
			# ---------------------------------------------------------------------------------
			# [Subset 6 Logistic Regression on Upper River]: 9. model with 9 variables: ["new_part"], ["Temp"], ["Rel_dsch_WY"], ["SY"], ["macro.type"], ["Segment"], ["Stk_120_cnt"] & ["Season"] and another one (three variables):  "new_part" is the seventh best single with "Stk_120_cnt", "Season", "Segment", ["macro.type"], ["SY"], ["Rel_dsch_WY"], ["Temp"]
			# ---------------------------------------------------------------------------------
			no.tmp  <- length(c(X.var.num,X.var.cat))
			idx.tmp <- 0
			for (X.var.rm in  grep("Rel_dsch_WY",grep("T_dist_up",grep("SY",grep("Seg",grep("Season",grep("macro.type",grep("Rel_dsch_AY",grep("Stk_120_cnt",c(X.var.num,X.var.cat),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE),value=TRUE,invert=TRUE))		# all variables other than  "Temp","Rel_dsch_WY", "SY", "macro.type", "Seg", "Season", "Stk_120_cnt",
			{
				idx.tmp <- idx.tmp + 1
				idx.var.rm <- match(X.var.rm,names(myData.Work))										# the index of the variable to be removed in the data frame
				if(!(is.na(idx.var.rm)))
				{
					model.count  <- model.count + 1
					myData.Tmp   <- myData.Work[,c("binary","Stk_120_cnt","Rel_dsch_AY","macro.type","Season","Seg","SY","T_dist_up","Rel_dsch_WY",X.var.rm)]			# eight variable combinations: "Temp","Rel_dsch_WY", "SY", "macro.type", "Seg","Stk_120_cnt", "Season" and the other
					model.Tmp    <- glm(binary ~ .,data=myData.Tmp,family=binomial("logit"))
					model.ID     <- X.var.rm
					model.string <- paste("Model",model.count," with ",X.var.rm," & Stk_120_cnt/Rel_dsch_AY/macro.type/Season/Seg/SY/T_dist_up/Rel_dsch_WY\n",sep=" ")
					model.no.var <- dim(myData.Tmp)[2] - 1
					model.rm.var <- paste("all but Stk_120_cnt/Rel_dsch_AY/macro.type/Season/Seg/SY/T_dist_up/Rel_dsch_WY & ",X.var.rm,sep=" ")
	
					model.formula       <- summary(model.Tmp)$call
					model.coef          <- as.data.frame(summary(model.Tmp)$coef)
					model.sum           <- c(summary(model.Tmp)$df.null,		 # null.df        
								 summary(model.Tmp)$df.residual,	 # resi.df        
								 summary(model.Tmp)$null.deviance,	 # null.deviance  
								 summary(model.Tmp)$deviance,		 # resi.deviance  
								 summary(model.Tmp)$aic,		 # aic            
								 summary(model.Tmp)$iter)		 # iter     
					model.data.fit      <- cbind(model.Tmp$data,fitted.value=model.Tmp$fitted.values,residual=model.Tmp$residual)		                         
	
					summary.this <- model.output(model.ID,model.string,model.count,model.no.var,model.formula,model.coef,model.sum,model.data.fit,model.rm.var)
	
					if (model.count == 1){summary.out <- summary.this}else{summary.out <- rbind(summary.out,summary.this)}
					
					# assign the model coefficienct to an object 
					command.string <- paste(paste("MODEL.9_",X.var.rm,sep="")," <- model.coef",sep="")
					eval(parse(text=command.string))
					
	
				      # save.command <- paste(save.command,",",paste("MODEL.9_",X.var.rm,sep=""),sep="")				# for all other model than the last one
				      # save.command <- paste(save.command,",",paste("MODEL.9_",X.var.rm,sep=""),",file=\"",FL.OUT.Obj,"\")",sep="")	# FOR THE LAST MODEL
				}
			}
			cat(paste("9. model with the best one and another one variable\n",sep=""))
			cat(paste("9. model with the best one and another one variable\n",sep=""),file=FL.LOG,append=TRUE)		
					
			
				
		# ---------------------------------------------------------------------------------
		# last: save all coefficients of all models
		# ---------------------------------------------------------------------------------
		# eval(parse(text=save.command))
			
		# write summary of all MODEL out to the summary file
		cat(paste("summary,",            sep=""),file=FL.OUT.Model,append=TRUE)
		write.table(data.frame(summary.out),file=FL.OUT.Model,row.names=TRUE,col.names=TRUE,sep=",",append=TRUE)
			 
	}else if (idx.subset == 7)	# Logistic Regression for the Lower River Stream
	{		
	}		 
}			 
			 
			 
# ---------------------- ---------------------------------------------------------------------------
# time used for completi# ng this script
# -------------------------------------------------------------------------------------------------
End.time  <- Sys.time()
Diff.time <- End.time - Start.time
Diff.time

cat(paste("\n14_VariableSelection_Subset6_final.R is finished successfully at ",End.time,"!\n",sep=" "))
cat(paste("\n14_VariableSelection_Subset6_final.R is finished successfully at ",End.time,"!\n",sep=" "),file=FL.LOG,append=TRUE)

cat(paste("\nProcessing time for [14_VariableSelection_Subset6_final.R] is ",as.numeric(Diff.time, units="mins")," minutes\n",sep=" "))
cat(paste("\nProcessing time for [14_VariableSelection_Subset6_final.R] is ",as.numeric(Diff.time, units="mins")," minutes\n",sep=" "),file=FL.LOG,append=TRUE)

#
# put run related information into the log file
#
cat(paste("This run was conducted in ",.Platform$OS.type,"\n",sep=""));
cat(paste("This run was conducted in ",.Platform$OS.type,"\n",sep=""),file=FL.LOG,append=TRUE);

# get the version of R used for this computation and the latest version released
current.Rversion <- R.Version()$version.string
tmp = readLines("http://cran.r-project.org/sources.html")
rls = tmp[grep("latest release", tmp) + 1L]			# the version number is in the next line of 'The latest release'
latest.Rversion  <- gsub("(.*R-|\\.tar\\.gz.*)", "", rls)	# "The latest release: R-2.13.0.tar.gz"
if (latest.Rversion != current.Rversion)
{
	cat(paste("\n\nyou may want to upgrade R from the version you are using [",current.Rversion,"] to the latest version of [",latest.Rversion,"]\n",sep=""));
	cat(paste("\n\nyou may want to upgrade R from the version you are using [",current.Rversion,"] to the latest version of [",latest.Rversion,"]\n",sep=""),file=FL.LOG,append=TRUE);
}else{
	cat(paste("\n\nThe R version you are using is the latest version released so far!\n",sep=""))
	cat(paste("\n\nThe R version you are using is the latest version released so far!\n",sep=""),file=FL.LOG,append=TRUE)
}

# get the version information of the attached libraries
cat(paste("\n\nThe information of the packages you used for this calculation:\n"))
cat(paste("\n\nThe information of the packages you used for this calculation:\n"),file=FL.LOG,append=TRUE)
tmp <- sessionInfo()
pkg.loaded <- tmp$otherPkgs
no.pkg.loaded <- length(pkg.loaded)
for (i in seq(1,no.pkg.loaded))
{
	cat(paste(pkg.loaded[[i]]$Package,":",pkg.loaded[[i]]$Version," ",pkg.loaded[[i]]$Date,"\n",sep=" "))
	cat(paste(pkg.loaded[[i]]$Package,":",pkg.loaded[[i]]$Version," ",pkg.loaded[[i]]$Date,"\n",sep=" "),file=FL.LOG,append=TRUE)
}






